# Copyright (c) 2020 Timmy109.
# Copyright (c) 2020 Contributors.
# Github profile: https://github.com/AusTechDev/
# Spigot Profile: https://www.spigotmc.org/members/_timmyy_.919057/
# Discord Server: https://discord.austech.dev/

# Config version - Please don't touch this!
config-version: 1

# Enable / Disable the use of player or bug reports
player-reports: true
bug-reports: true

# If a player report was successfully submitted, this message will be displayed in chat to the player
player-report-success: |-
  &8&l&m---------------------------------
  &a&lThank you! &aYour report has been submitted
  &a    Your reports help the community!
  &8&l&m---------------------------------

# If a bug report was successfully submitted, this message will be displayed in chat to the player
bug-report-success: |-
  &8&l&m---------------------------------
  &a&lThank you! &aYour report has been submitted
  &a    Your reports help the community!
  &8&l&m---------------------------------

# If a PLAYER report was successfully written to the file, notify staff with this message in chat
# You may use the {player} placeholder to get the reporter's name and the {report} placeholder to get the reason.
# The {target} placeholder is available to display the reported player's username.
staff-player-report-message: |-
  &8&l&m-----------------------------
  &c&l        NEW PLAYER REPORT
  &c&l      Submitted by: &7{player}
  &8     Check Discord for more details!
  &8&l&m-----------------------------

# If a BUG report was successfully written to the file, notify staff with this message in chat
# You may use the {player} placeholder to get the reporter's name and the {report} placeholder to get the reason.
staff-bug-report-message: |-
  &8&l&m---------------------------
  &c&l        NEW BUG REPORT
  &c&l      Submitted by: &7{player}
  &8     Check Discord for more details!
  &8&l&m---------------------------

# The message displayed when a player with the base permission node "betterreports.use" types in the base command /report.
player-help-message: |-
  &8&l&m-------------------------------
  &c&l&o        Better&4&l&oReports
  &8    Reporting bugs & players
  &7/report <player> <reason> &c Report a player
  &7/reportbug <bug> &c Report a bug
  &8&l&m-------------------------------

# The message displayed when a player with the permission node "betterreports.admin" types in the base command: /report.
admin-help-message: |-
  &8&l&m-------------------------------
  &c&l&o        Better&4&l&oReports
  &8    Reporting bugs & players
  &7/report <player> <reason> &c Report a player
  &7/reportbug <bug> &c Report a bug
  &7/br reload &c Reload the configuration
  &8&l&m-------------------------------

# Paste your Discord channel webhooks into the respective lines below
discord-bug-webhook-url: "https://discord.com/api/webhooks/786586736204840990/FmsKQdSqNZ9lqF3fmXyIjulDmuU0yVKlcXti8cbvGucsOsTs_XM-Zb4FLwueh1xq9WB0"
discord-player-webhook-url: "https://discord.com/api/webhooks/786586736204840990/FmsKQdSqNZ9lqF3fmXyIjulDmuU0yVKlcXti8cbvGucsOsTs_XM-Zb4FLwueh1xq9WB0"

# -----------------------------------------------------------------------------------
# Configuring the fields for the Discord webhook
# Follow this example:
#
# bug-report-fields:
#   1:
#    title: <title for the field>
#    content: <field content here>
#    inline: <true/false>
#
# Please note that Discord limitations mean that there can only be up to 25 fields!
# -----------------------------------------------------------------------------------

# Player report embed configuration
# Available placeholders: {player} (reporter), {report} (report content/bug)
bug-report-fields:
  1:
    title: "**Reports**"
    content: "Reported by: `{player}`"
    inline: false
  2:
    title: "Report Type"
    content: "Bug report"
    inline: false
  3:
    title: "Bug"
    content: "{report}"
    inline: false

# Set the embed footer of the bug report
bug-report-embed-footer: "AusTech - BetterReports"
bug-report-embed-icon: "https://cdn.discordapp.com/icons/749536377020088361/b8d4bada3908ccb2bac76773489ee0cf.png"

# Player report embed configuration
# Available placeholders: {player} (reporter), {target} (reported player), {report} (report content/reason)
player-report-fields:
  1:
    title: "**Reports**"
    content: "Reported by: `{player}`"
    inline: false
  2:
    title: "Report Type"
    content: "Player report"
    inline: false
  3:
    title: "Reported Player"
    content: "`{target}`"
    inline: false
  4:
    title: "Reason"
    content: "{report}"
    inline: false

# Set the embed footer of the player report
player-report-embed-footer: "AusTech - BetterReports"
player-report-embed-icon: "https://cdn.discordapp.com/icons/749536377020088361/b8d4bada3908ccb2bac76773489ee0cf.png"

# Webhook embed colour
# Put a hex code (Including the #) into the respective lines below
# Make sure there are no spaces otherwise this may break!
discord-embed-bug-report-colour: "#F0FF00"
discord-embed-player-report-colour: "#C761DF"

# Change the value below to change the length of the cooldown
# The value is in seconds!
report-bug-cooldown: 60
report-player-cooldown: 60

# Message Customisation
no-permission-message: "&cYou do not have permission to execute this command!"
error-sending-message: "&cError sending the bug report to discord. Please contact the admin."
player-only-message: "&cOnly players can execute that command!"
no-reason-message: "&cPlease specify a reason for reporting!"
no-bug-provided-message: "&cPlease specify the bug you would like to report!"
report-self-message: "&cYou can't report yourself!"
not-online-message: "&cPlayer has to be online to be reported!"
cannot-report-message: "&cYou cannot report that player!"
unknown-command: "&cUnknown Command!"

check-for-updates: true



