name: BetterReports
version: ${version}
main: dev.austech.betterreports.BetterReports
description: Reporting plugin with Discord webhook
commands:
  report:
    description: Report something!
  reportplayer:
    description: Report someone!
  reportbug:
    description: Report a bug!
  betterreports:
    description: Admin Command!
    aliases: [ br, breports ]
permissions:
  betterreports.use:
    description: Use the base commands
  betterreports.use.player:
    description: Report players
  betterreports.use.bug:
    description: Report bugs
  betterreports.admin:
    description: Admin commands
    default: op
  betterreports.alerts:
    description: Receive report alerts
    default: op
  betterreports.reload:
    description: Reload the configuration
    default: op
  betterreports.cooldown.bypass:
    description: Bypass the cooldown for reporting
    default: op
  betterreports.exempt:
    description: Exempt from being reported
    default: op

softdepend: [ PlaceholderAPI ]